spring.application.name=swaraj
server.port = 8088

# Enable the H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Database Connection (Choose ONE URL mode below)
# Mode A: In-Memory (Data is lost on shutdown)
spring.datasource.url=jdbc:h2:mem:customerdb

# Mode B: File-Based (Data persists in your user home directory)
# spring.datasource.url=jdbc:h2:file:~/data/testdb

# Credentials & Driver
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=Swaraj
spring.datasource.password=Swaraj@123

# Hibernate/JPA settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
